version: '3.8'

services:
  backend:
    build:
      context: .
    ports:
      - 8002:8002
    volumes:
      -./:/app/
  
  db:
    image: postgres
    restart: always
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_PASSWORD=volibear
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    