# Generated by Django 4.1.7 on 2023-07-29 23:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Circuit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=25)),
                ('slug', models.SlugField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=25)),
                ('slug', models.SlugField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EgliseLocal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=25)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('circuit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.circuit')),
            ],
        ),
        migrations.CreateModel(
            name='Famille',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_famille', models.CharField(blank=True, max_length=20)),
                ('nom_famille', models.CharField(max_length=100)),
                ('pid', models.CharField(blank=True, max_length=20)),
                ('details', models.JSONField(blank=True, null=True)),
                ('eglise_local', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.egliselocal')),
            ],
        ),
        migrations.CreateModel(
            name='Membre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_membre', models.CharField(blank=True, max_length=20)),
                ('nom', models.CharField(max_length=25)),
                ('prenoms', models.CharField(max_length=25)),
                ('date_naissance', models.DateField()),
                ('lieu_naissance', models.CharField(max_length=100)),
                ('occupation', models.CharField(default='', max_length=100)),
                ('formation', models.CharField(default='', max_length=100)),
                ('niveau_formation', models.CharField(default='', max_length=100)),
                ('genre', models.CharField(choices=[('M', 'Masculin'), ('F', 'Feminin')], default='M', max_length=10)),
                ('pid', models.CharField(blank=True, max_length=20)),
                ('image', models.ImageField(upload_to='profile/')),
                ('role', models.CharField(default='Membre', max_length=10)),
                ('situation_matrimoniale', models.CharField(default='Celibataire', max_length=20)),
                ('situation_familliale', models.CharField(default='Sans enfant', max_length=20)),
                ('details', models.JSONField(blank=True, null=True)),
                ('contact', models.CharField(blank=True, max_length=20)),
                ('egliseLocal', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.egliselocal')),
                ('enregistreur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enregistres', to=settings.AUTH_USER_MODEL)),
                ('famille', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.famille')),
            ],
        ),
        migrations.CreateModel(
            name='SouscriptionIndividu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.PositiveBigIntegerField(default=0)),
                ('numero', models.IntegerField(default=0)),
                ('date', models.DateField()),
                ('membre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.membre')),
            ],
        ),
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.PositiveBigIntegerField(default=0)),
                ('numero', models.IntegerField(default=0)),
                ('date', models.DateField()),
                ('famille', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.famille')),
                ('membre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.membre')),
            ],
        ),
        migrations.AddField(
            model_name='circuit',
            name='district',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.district'),
        ),
    ]
