# Generated by Django 4.1.7 on 2023-07-30 00:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membre',
            name='egliseLocal',
        ),
        migrations.AddField(
            model_name='membre',
            name='eglise_local',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.egliselocal'),
        ),
    ]
